name: Build App

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        shell: bash
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyinstaller
          pip install -r requirements.txt
      - name: Building CLI
        run: |
          pyinstaller --name=LASInfoDensityAvg-${{ steps.tag.outputs.tag }} --onefile --console main.py
      - name: Zip release
        run: |
          cd dist
          7z a LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip LASInfoDensityAvg-${{ steps.tag.outputs.tag }}.exe
          cd -
      - name: Upload Zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip
          path: dist/LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip

  Release:
    needs: [Windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Detect prerelease
        id: prerelease
        run: |
          if echo ${{ steps.tag.outputs.tag }} | grep -qe '?*.*.*rc*'; then
              echo ::set-output name=prerelease::true
          else
              echo ::set-output name=prerelease::false
          fi
      - name: Download Windows zip release file
        uses: actions/download-artifact@master
        with:
          name: LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip
          path: dist/LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
      - name: Upload Windows zip release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip/LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip
          asset_name: LASInfoDensityAvg-${{ steps.tag.outputs.tag }}-win64.zip
          asset_content_type: application/zip